const {PGlite}=await import(process.env.PGLITE_MODULE ?? '@electric-sql/pglite');
import {readFileSync} from 'node:fs';
const pg=new PGlite();
await pg.exec(`create role anon; create role authenticated; create role service_role;
create schema auth; create schema mangaro_private; grant usage on schema mangaro_private to anon,authenticated;
create table auth.users(id uuid primary key,is_anonymous boolean default false,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated,anon;
create table public.community_comments(id uuid primary key,user_id uuid references auth.users(id),parent_comment_id uuid,body text,target_type text);
create table public.community_comment_likes(comment_id uuid references community_comments(id),user_id uuid references auth.users(id),primary key(comment_id,user_id));
create table public.community_ratings(id uuid primary key,user_id uuid references auth.users(id),manga_key text,target_type text,rating int);
create function public.community_profile_complete() returns boolean language sql as $$select auth.uid() is not null$$;
alter table community_comment_likes enable row level security;
create policy community_likes_read on community_comment_likes for select using(true);
create policy community_likes_insert on community_comment_likes for insert to authenticated with check(user_id=auth.uid());
create policy community_likes_delete on community_comment_likes for delete to authenticated using(user_id=auth.uid());
grant select on community_comments,community_ratings,community_comment_likes to authenticated,anon;
grant insert,delete on community_comment_likes to authenticated;
`);
const path=process.argv[2]; await pg.exec(readFileSync(path,'utf8'));
const a='11111111-1111-1111-1111-111111111111',b='22222222-2222-2222-2222-222222222222';
await pg.exec(`insert into auth.users values('${a}',false,now()),('${b}',false,now()); insert into community_comments values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','${a}',null,'valid','manga');`);
await pg.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
const facts=[{key:'1'.repeat(64),kind:'work',work:'',genres:['romance'],started:true,library:true},{key:'2'.repeat(64),kind:'chapter',work:'1'.repeat(64),genres:['romance'],read:true,downloaded:true,bookmarked:true}];
let x=await pg.query(`select public.sigils_reconcile($1::jsonb) as data`,[JSON.stringify(facts)]);
if(!x.rows[0].data.unlocks.some(x=>x.id==='gates_awakened')) throw Error('read unlock missing');
if(x.rows[0].data.community.social_revered!==0) throw Error('wrong like progress');
await pg.query(`select public.sigils_reconcile($1::jsonb)`,[JSON.stringify(facts)]);
x=await pg.query('select count(*)::int as n from realm_sigil_facts'); if(x.rows[0].n!==2) throw Error('duplicate facts');
await pg.query(`select public.sigils_equip($1::jsonb,0)`,[JSON.stringify(['gates_awakened',null,null])]);
async function rejected(sql,args=[],label='') {let rejected=false;try {await pg.query(sql,args)}catch{rejected=true}if(!rejected)throw Error('should reject '+label)}
await rejected(`select public.sigils_equip($1::jsonb,1)`,[JSON.stringify(['gates_awakened','gates_awakened',null])],'duplicate slots');
await rejected(`select public.sigils_equip($1::jsonb,1)`,[JSON.stringify(['gates_guardian',null,null])],'locked badge');
await rejected(`select public.community_like_comment('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',true)`,[],'self like');
await rejected(`insert into realm_sigil_unlocks values('${a}','gates_guardian',0,false,null)`,[],'forged unlock');
await rejected(`select mangaro_private.sigil_award('${a}',false)`,[],'private award');
await pg.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);
x=await pg.query('select count(*)::int as n from realm_sigil_facts');if(x.rows[0].n!==0)throw Error('account leak');
await pg.query(`select public.community_like_comment('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',true)`);
await pg.query(`select public.community_like_comment('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',true)`);
x=await pg.query('select count(*)::int as n from community_comment_likes');if(x.rows[0].n!==1)throw Error('duplicate likes');
await pg.query(`select public.community_like_comment('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',false)`);
await pg.exec('reset role');
// 200 on two comments combined must NOT unlock; 200 on one must unlock.
await pg.exec(`insert into community_comments values('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','${a}',null,'second','manga');
insert into auth.users select ('00000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,false,now() from generate_series(1,200) i;
insert into community_comment_likes select 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',('00000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid from generate_series(1,100) i;
insert into community_comment_likes select 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',('00000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid from generate_series(101,200) i;`);
x=await pg.query(`select count(*)::int as n from realm_sigil_unlocks where user_id='${a}' and sigil_id='social_revered'`);if(x.rows[0].n)throw Error('distributed likes counted');
await pg.exec(`insert into community_comment_likes select 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',('00000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid from generate_series(101,200) i;`);
x=await pg.query(`select count(*)::int as n from realm_sigil_unlocks where user_id='${a}' and sigil_id='social_revered'`);if(x.rows[0].n!==1)throw Error('200 on single comment missing');
await pg.exec(`delete from community_comment_likes;`);
x=await pg.query(`select count(*)::int as n from realm_sigil_unlocks where user_id='${a}' and sigil_id='social_revered'`);if(x.rows[0].n!==1)throw Error('permanent unlock lost');
// All 30 server requirements, with isolated synthetic facts and authoritative social rows.
const numberKey=n=>n.toString(16).padStart(64,'0');
const tags=['martial_arts','romance','historical','regression','fantasy'];
const batch=[];
for(let i=0;i<20;i++) batch.push({key:numberKey(10000+i),kind:'work',genres:tags,started:i<10,library:true,organized:i<10});
for(let i=0;i<3;i++) batch.push({key:numberKey(20000+i),kind:'category'});
for(let i=0;i<1000;i++) batch.push({key:numberKey(30000+i),kind:'chapter',work:numberKey(10000+Math.floor(i/100)),genres:tags,read:true,bookmarked:i<20,downloaded:i<100});
await pg.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${a}',false);`);
for(let i=0;i<batch.length;i+=200) await pg.query('select public.sigils_reconcile($1::jsonb)',[JSON.stringify(batch.slice(i,i+200))]);
// A stale device cannot overwrite a newer equipment edit.
x=await pg.query('select public.sigils_equip($1::jsonb,0) as d',[JSON.stringify(['archive_gem',null,null])]);
if(x.rows[0].d.saved!==false)throw Error('stale equipment overwrote revision');
await pg.exec('reset role');
await pg.exec(`insert into community_comments select ('10000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,'${a}',null,'valid comment','manga' from generate_series(1,50) i;
insert into community_comments select ('20000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,'${a}','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','valid reply','manga' from generate_series(1,30) i;
insert into community_ratings select ('30000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,'${a}',i::text,'manga',5 from generate_series(1,20) i;`);
x=await pg.query(`select count(*)::int as n from realm_sigil_unlocks where user_id='${a}' and not revoked`);
if(x.rows[0].n!==30) throw Error('not all thirty server achievements unlocked: '+x.rows[0].n);
// Invalid/anonymous accounts are never eligible likers, even with a JWT role.
await pg.exec(`insert into auth.users values('cccccccc-cccc-cccc-cccc-cccccccccccc',true,null);
set role authenticated; select set_config('request.jwt.claim.sub','cccccccc-cccc-cccc-cccc-cccccccccccc',false);`);
await rejected(`select public.community_like_comment('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',true)`,[],'anonymous like');
await pg.exec('reset role');
await pg.exec(`set role anon;`);await rejected('select * from realm_sigil_unlocks',[],'private collection public');
x=await pg.query(`select public.sigils_public_slots('${a}') as slots`);if(x.rows[0].slots[0]!=='gates_awakened')throw Error('public equipment missing');
await pg.exec('reset role');
await pg.query(`select mangaro_private.revoke_sigil('${a}','gates_awakened','verified moderation')`);
x=await pg.query(`select public.sigils_public_slots('${a}') as slots`);if(x.rows[0].slots[0]!==null)throw Error('revoked equipped remains visible');
console.log('PASS: SQL migration, ALL 30 real thresholds, revision conflicts, anonymous rejection, permanent unlocks, 200 SINGLE-comment likes, RLS isolation, no self-like, idempotency, slots, private/public projection, moderation.');
await pg.close();
