package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Default theme
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #2979FF
 * Secondary #2979FF
 * Tertiary #47A84A
 * Neutral #919094
 */
internal object TachiyomiColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFA78BFA),
        onPrimary = Color(0xFF0B0D13),
        primaryContainer = Color(0xFF1B1F2B),
        onPrimaryContainer = Color(0xFFA78BFA),
        inversePrimary = Color(0xFFA78BFA),
        secondary = Color(0xFF67E8F9), // Unread badge
        onSecondary = Color(0xFF0B0D13), // Unread badge text
        secondaryContainer = Color(0xFF1B1F2B), // Navigation bar selector pill & pro
        onSecondaryContainer = Color(0xFF67E8F9), // Navigation bar selector icon
        tertiary = Color(0xFF67E8F9), // Downloaded badge
        onTertiary = Color(0xFF0B0D13), // Downloaded badge text
        tertiaryContainer = Color(0xFF1B1F2B),
        onTertiaryContainer = Color(0xFF67E8F9),
        background = Color(0xFF0B0D13),
        onBackground = Color(0xFFF5F6FA),
        surface = Color(0xFF12151E),
        onSurface = Color(0xFFF5F6FA),
        surfaceVariant = Color(0xFF1B1F2B), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFFA1A8B8),
        surfaceTint = Color(0xFFA78BFA),
        inverseSurface = Color(0xFFF5F6FA),
        inverseOnSurface = Color(0xFF0B0D13),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF8F9099),
        outlineVariant = Color(0xFF44464F),
        surfaceContainerLowest = Color(0xFF0B0D13),
        surfaceContainerLow = Color(0xFF0B0D13),
        surfaceContainer = Color(0xFF12151E), // Navigation bar background
        surfaceContainerHigh = Color(0xFF1B1F2B),
        surfaceContainerHighest = Color(0xFF1B1F2B),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF0058CA),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD9E2FF),
        onPrimaryContainer = Color(0xFF001945),
        inversePrimary = Color(0xFFB0C6FF),
        secondary = Color(0xFF0058CA), // Unread badge
        onSecondary = Color(0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(0xFFD9E2FF), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(0xFF001945), // Navigation bar selector icon
        tertiary = Color(0xFF006E1B), // Downloaded badge
        onTertiary = Color(0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(0xFF95F990),
        onTertiaryContainer = Color(0xFF002203),
        background = Color(0xFFFEFBFF),
        onBackground = Color(0xFF1B1B1F),
        surface = Color(0xFFFEFBFF),
        onSurface = Color(0xFF1B1B1F),
        surfaceVariant = Color(0xFFF3EDF7), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFF44464F),
        surfaceTint = Color(0xFF0058CA),
        inverseSurface = Color(0xFF303034),
        inverseOnSurface = Color(0xFFF2F0F4),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF757780),
        outlineVariant = Color(0xFFC5C6D0),
        surfaceContainerLowest = Color(0xFFF5F1F8),
        surfaceContainerLow = Color(0xFFF7F2FA),
        surfaceContainer = Color(0xFFF3EDF7), // Navigation bar background
        surfaceContainerHigh = Color(0xFFFCF7FF),
        surfaceContainerHighest = Color(0xFFFCF7FF),
    )
}
